steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: "bash"
  args:
    - "-c"
    - |
        max_attempts=2
        attempt_num=1
        until gcloud builds submit --config cloudbuild-retry-dep.yaml . || [ $attempt_num -eq $max_attempts ]; do
          echo "Intento No. $attempt_num fallo! Intentando de nuevo en 5 segundos..."
          sleep 5
          attempt_num=$((attempt_num + 1))
        done
        if [ $attempt_num -eq $max_attempts ]; then
          echo "Todos los Intentos han sido erroneos!"
          exit 1
        fi
  id: curl_nuget_10_retry
options:
  pool:
    name: 'projects/came-devops-qa-421116/locations/us-central1/workerPools/m2c-qa-private-pool'