steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: "bash"
  args:
    - "-c"
    - |
      echo "PROJECT_ID: $PROJECT_ID"
      echo "SHORT_SHA: ${SHORT_SHA}"
      echo "SHORT_SHA: $SHORT_SHA"
      echo "------------------------------------------"
  id: ECHO
  env:
    - 'SHORTSHA=${SHORT_SHA}'
- name: gcr.io/cloud-builders/gcloud
  entrypoint: "bash"
  args:
    - "-c"
    - |
        max_attempts=2
        attempt_num=1
        until gcloud builds submit --config cloudbuild-uno.yaml . || [ $attempt_num -eq $max_attempts ]; do
          echo "Attempt $attempt_num failed! Trying again in 5 seconds..."
          sleep 5
          attempt_num=$((attempt_num + 1))
        done
        if [ $attempt_num -eq $max_attempts ]; then
          echo "All attempts failed!"
          exit 1
        fi
  id: curl_nuget_10_retry

options:
  pool:
    name: 'projects/came-devops-qa-421116/locations/us-central1/workerPools/m2c-qa-private-pool'