steps:
- name: 'bash'
  script: |
    #!/usr/bin/env bash
    ifconfig
  id: Show IP
- name: gcr.io/cloud-builders/gcloud
  entrypoint: "bash"
  args:
    - "-c"
    - |
        max_attempts=10
        attempt_num=1
        until curl -i --max-time 10 http://10.10.200.2/TcsNugetServer/nuget || [ $attempt_num -eq $max_attempts ]; do
          echo "Intento No. $attempt_num fallo! Intentando de nuevo en 5 segundos..."
          sleep 10
          attempt_num=$((attempt_num + 1))
        done
        if [ $attempt_num -eq $max_attempts ]; then
          echo "Todos los Intentos han sido erroneos!"
          exit 1
        fi
  id: curl_nuget_10_retry


# - name: gcr.io/cloud-builders/gcloud
#   entrypoint: "bash"
#   args:
#     - "-c"
#     - |
#         curl -i http://10.10.200.2/TcsNugetServer/nuget
#   id: curl_nuget_10
#   allowFailure: true

# - name: gcr.io/cloud-builders/gcloud
#   entrypoint: "bash"
#   args:
#     - "-c"
#     - |
#         curl http://192.168.101.28:8050/Desarrollo/_packaging/DESARROLLO_TEST/nuget/v3/index.json
# # curl --ntlm -u 'TKS\pharevalo:Jiha599*Js*' http://192.168.101.28:8050/Desarrollo/_packaging/DESARROLLO_TEST/nuget/v3/index.json
#   id: curl_nuget_198
#   allowFailure: true

options:
  pool:
    name: 'projects/came-devops-qa-421116/locations/us-central1/workerPools/m2c-qa-private-pool'
