steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: "bash"
  args:
    - "-c"
    - |
        max_attempts=
        attempt_num=1
        until gcloud builds submit --config cloudbuild-uno.yaml . || [ $attempt_num -eq $max_attempts ]; do
          echo "Attempt $attempt_num failed! Trying again in 5 seconds..."
          sleep 5
          attempt_num=$((attempt_num + 1))
        done
  id: curl_nuget_10_retry

# - name: gcr.io/cloud-builders/gcloud
#   entrypoint: "bash"
#   args:
#     - "-c"
#     - |
#         curl --ntlm -u 'TKS\pharevalo:Jiha599*Js*' http://192.168.101.28:8050/Desarrollo/_packaging/DESARROLLO_TEST/nuget/v3/index.json
#   id: curl_nuget_198

options:
  pool:
    name: 'projects/came-devops-qa-421116/locations/us-central1/workerPools/m2c-qa-private-pool'

  allow_failure: true