//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServDocumentos.Core.Mensajes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensajesServicios {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensajesServicios() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServDocumentos.Core.Mensajes.MensajesServicios", typeof(MensajesServicios).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontro el crédito .
        /// </summary>
        public static string CreditoNoEncontrado {
            get {
                return ResourceManager.GetString("CreditoNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrio Un error al Deserealizar el Objecto.
        /// </summary>
        public static string ErrorDeserealizacion {
            get {
                return ResourceManager.GetString("ErrorDeserealizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron documentos asociados al SubProceso..
        /// </summary>
        public static string ErrorObtenerDocumentos {
            get {
                return ResourceManager.GetString("ErrorObtenerDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE PRODUJO UN ERROR EN EL SERVIDOR.
        /// </summary>
        public static string ErrorServidor {
            get {
                return ResourceManager.GetString("ErrorServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAA7AAAAOwBeShxvQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAJoSURBVFiF7ddLiI1hHMfxj3FL7pcot8IshlhIpJRmSinFQpJEIllQrMhkFqzYyRopl1xCWdi5FSaxcilELmXBNI0RZcIYi/87zjtn3nPmnOM0LPzqWZz3PM///32f5//8nuelb23ET3RVsZ3vDj6oBICpeIpdJfQtReswpxwA+IRrVQJYmAaoqVLQipWege2oz+hTh8m4UCTOazTh+58AbMA33Mvr86qPGHOxB7VifcuG6FYzGisYtwnteI9LGNxH/8YkF3rWwA+V07ejAUtwrgSI30oDbMPxCgGIrVo2RBrgFT5WmLwGY8UyrE5ASoJIA5wWhViuvmAa2pJ2N4FZja19DU7vgs34WgHAZczQ21Mu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ImagenDinamicaError {
            get {
                return ResourceManager.GetString("ImagenDinamicaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ResultadoOK {
            get {
                return ResourceManager.GetString("ResultadoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio Campos.
        /// </summary>
        public static string ServicioCampos {
            get {
                return ResourceManager.GetString("ServicioCampos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio Clasificaciones.
        /// </summary>
        public static string ServicioClasificaciones {
            get {
                return ResourceManager.GetString("ServicioClasificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio Datos.
        /// </summary>
        public static string ServicioDatos {
            get {
                return ResourceManager.GetString("ServicioDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio Documentos.
        /// </summary>
        public static string ServicioDocumentos {
            get {
                return ResourceManager.GetString("ServicioDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio Externo.
        /// </summary>
        public static string ServicioExterno {
            get {
                return ResourceManager.GetString("ServicioExterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio Generales.
        /// </summary>
        public static string ServicioGenerales {
            get {
                return ResourceManager.GetString("ServicioGenerales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio Plantillas.
        /// </summary>
        public static string ServicioPlantillas {
            get {
                return ResourceManager.GetString("ServicioPlantillas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio Plantillas . Campos.
        /// </summary>
        public static string ServicioPlantillasCampos {
            get {
                return ResourceManager.GetString("ServicioPlantillasCampos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio Procesos.
        /// </summary>
        public static string ServicioProcesos {
            get {
                return ResourceManager.GetString("ServicioProcesos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio Procesos - Campos.
        /// </summary>
        public static string ServicioProcesosCampos {
            get {
                return ResourceManager.GetString("ServicioProcesosCampos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicios en Operación.
        /// </summary>
        public static string ServiciosFuncionando {
            get {
                return ResourceManager.GetString("ServiciosFuncionando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio SubProcesos.
        /// </summary>
        public static string ServicioSubProcesos {
            get {
                return ResourceManager.GetString("ServicioSubProcesos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servcio SubProcesos - Campos.
        /// </summary>
        public static string ServicioSubProcesosCampos {
            get {
                return ResourceManager.GetString("ServicioSubProcesosCampos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio SubProcesos - Plantillas.
        /// </summary>
        public static string ServicioSubProcesosPlantillas {
            get {
                return ResourceManager.GetString("ServicioSubProcesosPlantillas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.24.1.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
