//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServDocumentos.Repositorios.TCR.ServicioTcrCaja
{
    using ServDocumentos.Core.Contratos.Repositorios.TCR;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListaPendientes", Namespace="http://org.apache.synapse/xsd", ItemName="TransaccionPendiente")]
    public class ListaPendientes : System.Collections.Generic.List<ServicioTcrCaja.TransaccionPendiente>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransaccionPendiente", Namespace="http://org.apache.synapse/xsd")]
    public partial class TransaccionPendiente : object
    {
        
        private string TipoTransaccionField;
        
        private string NoCtaAhorroField;
        
        private string UsuarioField;
        
        private double MontoField;
        
        private string TerminalField;
        
        private string ServidorField;
        
        private string FormaField;
        
        private string CausalField;
        
        private string ObservacionesField;
        
        private double MontoBloqueoField;
        
        private string TipoDepositoRetiroField;
        
        private string OrigenField;
        
        private string IdentificadorReversaField;
        
        private string IdentificadorOrigenField;
        
        private long IdTransaccionField;
        
        private string SesionField;
        
        private string MotivoField;
        
        private string EstadoField;
        
        private System.DateTime FechaMovimientoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoTransaccion
        {
            get
            {
                return this.TipoTransaccionField;
            }
            set
            {
                this.TipoTransaccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string NoCtaAhorro
        {
            get
            {
                return this.NoCtaAhorroField;
            }
            set
            {
                this.NoCtaAhorroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double Monto
        {
            get
            {
                return this.MontoField;
            }
            set
            {
                this.MontoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Terminal
        {
            get
            {
                return this.TerminalField;
            }
            set
            {
                this.TerminalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Servidor
        {
            get
            {
                return this.ServidorField;
            }
            set
            {
                this.ServidorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Forma
        {
            get
            {
                return this.FormaField;
            }
            set
            {
                this.FormaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Causal
        {
            get
            {
                return this.CausalField;
            }
            set
            {
                this.CausalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string Observaciones
        {
            get
            {
                return this.ObservacionesField;
            }
            set
            {
                this.ObservacionesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public double MontoBloqueo
        {
            get
            {
                return this.MontoBloqueoField;
            }
            set
            {
                this.MontoBloqueoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string TipoDepositoRetiro
        {
            get
            {
                return this.TipoDepositoRetiroField;
            }
            set
            {
                this.TipoDepositoRetiroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string Origen
        {
            get
            {
                return this.OrigenField;
            }
            set
            {
                this.OrigenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string IdentificadorReversa
        {
            get
            {
                return this.IdentificadorReversaField;
            }
            set
            {
                this.IdentificadorReversaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string IdentificadorOrigen
        {
            get
            {
                return this.IdentificadorOrigenField;
            }
            set
            {
                this.IdentificadorOrigenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public long IdTransaccion
        {
            get
            {
                return this.IdTransaccionField;
            }
            set
            {
                this.IdTransaccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string Sesion
        {
            get
            {
                return this.SesionField;
            }
            set
            {
                this.SesionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string Motivo
        {
            get
            {
                return this.MotivoField;
            }
            set
            {
                this.MotivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public System.DateTime FechaMovimiento
        {
            get
            {
                return this.FechaMovimientoField;
            }
            set
            {
                this.FechaMovimientoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaReferencia", Namespace="http://schemas.datacontract.org/2004/07/TcrCaja.Entidades.MessageContracts")]
    public partial class RespuestaReferencia : object
    {
        
        private string Codigo128OxxoPayField;
        
        private string Codigo128PaynetField;
        
        private string Codigo128WalMartField;
        
        private int CodigoRespuestaField;
        
        private ServicioTcrCaja.DatosCreditoReferencia DatosCreditoField;
        
        private string MensajeField;
        
        private string NoReferenciaPaynetField;
        
        private string NoReferenciaWalMartField;
        
        private string ReferenciaOxxoPayField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo128OxxoPay
        {
            get
            {
                return this.Codigo128OxxoPayField;
            }
            set
            {
                this.Codigo128OxxoPayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo128Paynet
        {
            get
            {
                return this.Codigo128PaynetField;
            }
            set
            {
                this.Codigo128PaynetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo128WalMart
        {
            get
            {
                return this.Codigo128WalMartField;
            }
            set
            {
                this.Codigo128WalMartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoRespuesta
        {
            get
            {
                return this.CodigoRespuestaField;
            }
            set
            {
                this.CodigoRespuestaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicioTcrCaja.DatosCreditoReferencia DatosCredito
        {
            get
            {
                return this.DatosCreditoField;
            }
            set
            {
                this.DatosCreditoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoReferenciaPaynet
        {
            get
            {
                return this.NoReferenciaPaynetField;
            }
            set
            {
                this.NoReferenciaPaynetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoReferenciaWalMart
        {
            get
            {
                return this.NoReferenciaWalMartField;
            }
            set
            {
                this.NoReferenciaWalMartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenciaOxxoPay
        {
            get
            {
                return this.ReferenciaOxxoPayField;
            }
            set
            {
                this.ReferenciaOxxoPayField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosCreditoReferencia", Namespace="http://org.apache.synapse/xsd")]
    public partial class DatosCreditoReferencia : object
    {
        
        private int NoClienteField;
        
        private string NombreField;
        
        private string ProductoField;
        
        private string NoCreditoField;
        
        private string NoCuentaAhorroField;
        
        private string NombreComercialField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NoCliente
        {
            get
            {
                return this.NoClienteField;
            }
            set
            {
                this.NoClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Producto
        {
            get
            {
                return this.ProductoField;
            }
            set
            {
                this.ProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string NoCredito
        {
            get
            {
                return this.NoCreditoField;
            }
            set
            {
                this.NoCreditoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string NoCuentaAhorro
        {
            get
            {
                return this.NoCuentaAhorroField;
            }
            set
            {
                this.NoCuentaAhorroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string NombreComercial
        {
            get
            {
                return this.NombreComercialField;
            }
            set
            {
                this.NombreComercialField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosOperacionCredito", Namespace="http://schemas.datacontract.org/2004/07/TcrCaja.Entidades.Comunes")]
    public partial class DatosOperacionCredito : object
    {
        
        private string BeneficiarioField;
        
        private int CodigoRespuestaField;
        
        private string CuentaDestinoDesembolsadoField;
        
        private string CuentaVinculadaField;
        
        private string DireccionOficinaField;
        
        private System.DateTime FechaInicioField;
        
        private System.DateTime FechaUltimoProcesoField;
        
        private string FormaDesembolsoField;
        
        private string FormaDesembolsoDescripcionField;
        
        private long IdClienteField;
        
        private long IdEstadoField;
        
        private int IdOficinaField;
        
        private string MensajeRespuestaField;
        
        private double MontoBrutoField;
        
        private double MontoDesembolsoField;
        
        private string NombreClienteField;
        
        private string NombreComercialProductoField;
        
        private string NombreOficinaField;
        
        private string NumCreditoField;
        
        private string ProductoField;
        
        private ServicioTcrCaja.SeguroVoluntario[] SegurosVoluntariosField;
        
        private string TerminalField;
        
        private string TipoTablaAmortizacionField;
        
        private string UsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Beneficiario
        {
            get
            {
                return this.BeneficiarioField;
            }
            set
            {
                this.BeneficiarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoRespuesta
        {
            get
            {
                return this.CodigoRespuestaField;
            }
            set
            {
                this.CodigoRespuestaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaDestinoDesembolsado
        {
            get
            {
                return this.CuentaDestinoDesembolsadoField;
            }
            set
            {
                this.CuentaDestinoDesembolsadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaVinculada
        {
            get
            {
                return this.CuentaVinculadaField;
            }
            set
            {
                this.CuentaVinculadaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionOficina
        {
            get
            {
                return this.DireccionOficinaField;
            }
            set
            {
                this.DireccionOficinaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaInicio
        {
            get
            {
                return this.FechaInicioField;
            }
            set
            {
                this.FechaInicioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaUltimoProceso
        {
            get
            {
                return this.FechaUltimoProcesoField;
            }
            set
            {
                this.FechaUltimoProcesoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormaDesembolso
        {
            get
            {
                return this.FormaDesembolsoField;
            }
            set
            {
                this.FormaDesembolsoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormaDesembolsoDescripcion
        {
            get
            {
                return this.FormaDesembolsoDescripcionField;
            }
            set
            {
                this.FormaDesembolsoDescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdCliente
        {
            get
            {
                return this.IdClienteField;
            }
            set
            {
                this.IdClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdEstado
        {
            get
            {
                return this.IdEstadoField;
            }
            set
            {
                this.IdEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdOficina
        {
            get
            {
                return this.IdOficinaField;
            }
            set
            {
                this.IdOficinaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeRespuesta
        {
            get
            {
                return this.MensajeRespuestaField;
            }
            set
            {
                this.MensajeRespuestaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MontoBruto
        {
            get
            {
                return this.MontoBrutoField;
            }
            set
            {
                this.MontoBrutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MontoDesembolso
        {
            get
            {
                return this.MontoDesembolsoField;
            }
            set
            {
                this.MontoDesembolsoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCliente
        {
            get
            {
                return this.NombreClienteField;
            }
            set
            {
                this.NombreClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreComercialProducto
        {
            get
            {
                return this.NombreComercialProductoField;
            }
            set
            {
                this.NombreComercialProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreOficina
        {
            get
            {
                return this.NombreOficinaField;
            }
            set
            {
                this.NombreOficinaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumCredito
        {
            get
            {
                return this.NumCreditoField;
            }
            set
            {
                this.NumCreditoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Producto
        {
            get
            {
                return this.ProductoField;
            }
            set
            {
                this.ProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicioTcrCaja.SeguroVoluntario[] SegurosVoluntarios
        {
            get
            {
                return this.SegurosVoluntariosField;
            }
            set
            {
                this.SegurosVoluntariosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Terminal
        {
            get
            {
                return this.TerminalField;
            }
            set
            {
                this.TerminalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoTablaAmortizacion
        {
            get
            {
                return this.TipoTablaAmortizacionField;
            }
            set
            {
                this.TipoTablaAmortizacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeguroVoluntario", Namespace="http://schemas.datacontract.org/2004/07/TcrCaja.Entidades.Comunes")]
    public partial class SeguroVoluntario : object
    {
        
        private short CantidadField;
        
        private int ClienteIdField;
        
        private short EstadoSolicitudField;
        
        private System.DateTime FechaInicioField;
        
        private System.DateTime FechaVencimientoField;
        
        private int GrupoIdField;
        
        private long IdField;
        
        private short IdTextoMostrarField;
        
        private double MontoField;
        
        private string NoCertificadoField;
        
        private string NombreSeguroField;
        
        private long SolicitudIdField;
        
        private short TipoSeguroIdField;
        
        private string VigenciaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Cantidad
        {
            get
            {
                return this.CantidadField;
            }
            set
            {
                this.CantidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClienteId
        {
            get
            {
                return this.ClienteIdField;
            }
            set
            {
                this.ClienteIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short EstadoSolicitud
        {
            get
            {
                return this.EstadoSolicitudField;
            }
            set
            {
                this.EstadoSolicitudField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaInicio
        {
            get
            {
                return this.FechaInicioField;
            }
            set
            {
                this.FechaInicioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaVencimiento
        {
            get
            {
                return this.FechaVencimientoField;
            }
            set
            {
                this.FechaVencimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GrupoId
        {
            get
            {
                return this.GrupoIdField;
            }
            set
            {
                this.GrupoIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IdTextoMostrar
        {
            get
            {
                return this.IdTextoMostrarField;
            }
            set
            {
                this.IdTextoMostrarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Monto
        {
            get
            {
                return this.MontoField;
            }
            set
            {
                this.MontoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoCertificado
        {
            get
            {
                return this.NoCertificadoField;
            }
            set
            {
                this.NoCertificadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreSeguro
        {
            get
            {
                return this.NombreSeguroField;
            }
            set
            {
                this.NombreSeguroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SolicitudId
        {
            get
            {
                return this.SolicitudIdField;
            }
            set
            {
                this.SolicitudIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short TipoSeguroId
        {
            get
            {
                return this.TipoSeguroIdField;
            }
            set
            {
                this.TipoSeguroIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vigencia
        {
            get
            {
                return this.VigenciaField;
            }
            set
            {
                this.VigenciaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaOperacionesResponse", Namespace="http://schemas.datacontract.org/2004/07/TcrCaja.Entidades.MessageContracts")]
    public partial class ConsultaOperacionesResponse : object
    {
        
        private int CodigoRespuestaField;
        
        private string MensajeRespuestaField;
        
        private ServicioTcrCaja.OperacionTransaccion[] OperacionesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoRespuesta
        {
            get
            {
                return this.CodigoRespuestaField;
            }
            set
            {
                this.CodigoRespuestaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeRespuesta
        {
            get
            {
                return this.MensajeRespuestaField;
            }
            set
            {
                this.MensajeRespuestaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServicioTcrCaja.OperacionTransaccion[] Operaciones
        {
            get
            {
                return this.OperacionesField;
            }
            set
            {
                this.OperacionesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperacionTransaccion", Namespace="http://schemas.datacontract.org/2004/07/TcrCaja.Entidades.DataContracts")]
    public partial class OperacionTransaccion : object
    {
        
        private string EstadoField;
        
        private System.DateTime FechaField;
        
        private long IdField;
        
        private long IdTransaccionField;
        
        private decimal MontoField;
        
        private string TipoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdTransaccion
        {
            get
            {
                return this.IdTransaccionField;
            }
            set
            {
                this.IdTransaccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Monto
        {
            get
            {
                return this.MontoField;
            }
            set
            {
                this.MontoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo
        {
            get
            {
                return this.TipoField;
            }
            set
            {
                this.TipoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditoPreautorizado", Namespace="http://schemas.datacontract.org/2004/07/TcrCaja.Entidades.Comunes")]
    public partial class CreditoPreautorizado : object
    {
        
        private double CuotaPreautorizadoField;
        
        private System.DateTime FechaCalculoField;
        
        private int IdField;
        
        private int IdClienteField;
        
        private int IdOficinaField;
        
        private int IdRegionalField;
        
        private double MontoPreautorizadoField;
        
        private int NoOperacionCredField;
        
        private string NumCreditoField;
        
        private short PlazoPreautorizadoField;
        
        private double SaldoLiquidacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CuotaPreautorizado
        {
            get
            {
                return this.CuotaPreautorizadoField;
            }
            set
            {
                this.CuotaPreautorizadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCalculo
        {
            get
            {
                return this.FechaCalculoField;
            }
            set
            {
                this.FechaCalculoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente
        {
            get
            {
                return this.IdClienteField;
            }
            set
            {
                this.IdClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdOficina
        {
            get
            {
                return this.IdOficinaField;
            }
            set
            {
                this.IdOficinaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRegional
        {
            get
            {
                return this.IdRegionalField;
            }
            set
            {
                this.IdRegionalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MontoPreautorizado
        {
            get
            {
                return this.MontoPreautorizadoField;
            }
            set
            {
                this.MontoPreautorizadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoOperacionCred
        {
            get
            {
                return this.NoOperacionCredField;
            }
            set
            {
                this.NoOperacionCredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumCredito
        {
            get
            {
                return this.NumCreditoField;
            }
            set
            {
                this.NumCreditoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short PlazoPreautorizado
        {
            get
            {
                return this.PlazoPreautorizadoField;
            }
            set
            {
                this.PlazoPreautorizadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SaldoLiquidacion
        {
            get
            {
                return this.SaldoLiquidacionField;
            }
            set
            {
                this.SaldoLiquidacionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdenPagoData", Namespace="http://schemas.datacontract.org/2004/07/TcrCaja.Entidades.MessageContracts")]
    public partial class OrdenPagoData : object
    {
        
        private string BancoField;
        
        private string BeneficiarioField;
        
        private string ConceptoField;
        
        private int DiasVigenciaField;
        
        private System.DateTime FechaOperacionField;
        
        private System.DateTime FechaVigenciaField;
        
        private double MontoField;
        
        private string NoConvenioField;
        
        private string ReferenciaField;
        
        private int clienteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Banco
        {
            get
            {
                return this.BancoField;
            }
            set
            {
                this.BancoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Beneficiario
        {
            get
            {
                return this.BeneficiarioField;
            }
            set
            {
                this.BeneficiarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Concepto
        {
            get
            {
                return this.ConceptoField;
            }
            set
            {
                this.ConceptoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiasVigencia
        {
            get
            {
                return this.DiasVigenciaField;
            }
            set
            {
                this.DiasVigenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaOperacion
        {
            get
            {
                return this.FechaOperacionField;
            }
            set
            {
                this.FechaOperacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaVigencia
        {
            get
            {
                return this.FechaVigenciaField;
            }
            set
            {
                this.FechaVigenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Monto
        {
            get
            {
                return this.MontoField;
            }
            set
            {
                this.MontoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoConvenio
        {
            get
            {
                return this.NoConvenioField;
            }
            set
            {
                this.NoConvenioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referencia
        {
            get
            {
                return this.ReferenciaField;
            }
            set
            {
                this.ReferenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cliente
        {
            get
            {
                return this.clienteField;
            }
            set
            {
                this.clienteField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tecreemos.wcf.caja/xsd", ConfigurationName="ServicioTcrCaja.TcrCajaService")]
    public interface TcrCajaService
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tecreemos.wcf.caja/xsd/ObtienePendientes", ReplyAction="http://tecreemos.wcf.caja/xsd/TcrCajaService/ConsultaPendientesCajaResponse")]
        System.Threading.Tasks.Task<ServicioTcrCaja.ConsultaPendientesResponse> ConsultaPendientesCajaAsync(ServicioTcrCaja.ConsultaPendientesCajaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tecreemos.wcf.caja/xsd/RefrescaParametros", ReplyAction="http://tecreemos.wcf.caja/xsd/TcrCajaService/RefrescaParametrosResponse")]
        System.Threading.Tasks.Task RefrescaParametrosAsync();
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tecreemos.wcf.caja/xsd/ActualizaTablaAmortizacionAFechaProc", ReplyAction="http://tecreemos.wcf.caja/xsd/TcrCajaService/ActualizaTablaAmortizacionAFechaProc" +
            "Response")]
        System.Threading.Tasks.Task<ServicioTcrCaja.ActualizaTablaAmortizacionAFechaProcResponse> ActualizaTablaAmortizacionAFechaProcAsync(ServicioTcrCaja.ActualizaTablaAmortizacionAFechaProcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tecreemos.wcf.caja/xsd/ConsultaParametrosEspeciales", ReplyAction="http://tecreemos.wcf.caja/xsd/TcrCajaService/ConsultaParametrosEspecialesResponse" +
            "")]
        System.Threading.Tasks.Task<string> ConsultaParametrosEspecialesAsync(string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tecreemos.wcf.caja/xsd/GeneraReferenciaPago", ReplyAction="http://tecreemos.wcf.caja/xsd/TcrCajaService/GeneraReferenciaPagoResponse")]
        System.Threading.Tasks.Task<ServicioTcrCaja.RespuestaReferencia> GeneraReferenciaPagoAsync(string numCredito, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tecreemos.wcf.caja/xsd/ConsultaDatosOperacionCredito", ReplyAction="http://tecreemos.wcf.caja/xsd/TcrCajaService/ConsultaDatosOperacionCreditoRespons" +
            "e")]
        System.Threading.Tasks.Task<ServicioTcrCaja.DatosOperacionCredito> ConsultaDatosOperacionCreditoAsync(string numCredito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tecreemos.wcf.caja/xsd/ConsultaDatosOperacionTransaccion", ReplyAction="http://tecreemos.wcf.caja/xsd/TcrCajaService/ConsultaOperacionTransaccionResponse" +
            "")]
        System.Threading.Tasks.Task<ServicioTcrCaja.ConsultaOperacionesResponse> ConsultaOperacionTransaccionAsync(string numCredito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tecreemos.wcf.caja/xsd/ConsultaCreditoPreautorizado", ReplyAction="http://tecreemos.wcf.caja/xsd/TcrCajaService/ConsultaCreditoPreautorizadoResponse" +
            "")]
        System.Threading.Tasks.Task<ServicioTcrCaja.CreditoPreautorizado> ConsultaCreditoPreautorizadoAsync(string numCredito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tecreemos.wcf.caja/xsd/ActualizaEstadoOffLine", ReplyAction="http://tecreemos.wcf.caja/xsd/TcrCajaService/ActualizaEstadoTranOffLineResponse")]
        System.Threading.Tasks.Task<string> ActualizaEstadoTranOffLineAsync(long idOffline, string nuevoEstadoOffline, string motivo);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tecreemos.wcf.caja/xsd/ObtieneDatosOrdenPago", ReplyAction="http://tecreemos.wcf.caja/xsd/TcrCajaService/ObtieneDatosOrdenPagoResponse")]
        System.Threading.Tasks.Task<ServicioTcrCaja.DatosOrdenPagoResponse> ObtieneDatosOrdenPagoAsync(ServicioTcrCaja.DatosOrdenPagoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaPendientesCajaRequest
    {
        
        public ConsultaPendientesCajaRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaPendientesResponse", WrapperNamespace="http://tecreemos.wcf.caja/xsd", IsWrapped=true)]
    public partial class ConsultaPendientesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tecreemos.wcf.caja/xsd", Order=0)]
        public int CodigoRespuesta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tecreemos.wcf.caja/xsd", Order=1)]
        public string Mensaje;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tecreemos.wcf.caja/xsd", Order=2)]
        public ServicioTcrCaja.ListaPendientes Pendientes;
        
        public ConsultaPendientesResponse()
        {
        }
        
        public ConsultaPendientesResponse(int CodigoRespuesta, string Mensaje, ServicioTcrCaja.ListaPendientes Pendientes)
        {
            this.CodigoRespuesta = CodigoRespuesta;
            this.Mensaje = Mensaje;
            this.Pendientes = Pendientes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizaTablaAmortizacionAFechaProc", WrapperNamespace="http://tecreemos.wcf.caja/xsd", IsWrapped=true)]
    public partial class ActualizaTablaAmortizacionAFechaProcRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tecreemos.wcf.caja/xsd", Order=0)]
        public string NumCredito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tecreemos.wcf.caja/xsd", Order=1)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tecreemos.wcf.caja/xsd", Order=2)]
        public string Terminal;
        
        public ActualizaTablaAmortizacionAFechaProcRequest()
        {
        }
        
        public ActualizaTablaAmortizacionAFechaProcRequest(string NumCredito, string Usuario, string Terminal)
        {
            this.NumCredito = NumCredito;
            this.Usuario = Usuario;
            this.Terminal = Terminal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizaTablaAmortizacionAFechaProcResponse", WrapperNamespace="http://tecreemos.wcf.caja/xsd", IsWrapped=true)]
    public partial class ActualizaTablaAmortizacionAFechaProcResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tecreemos.wcf.caja/xsd", Order=0)]
        public bool ActualizaTablaAmortizacionAFechaProcResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tecreemos.wcf.caja/xsd", Order=1)]
        public string mensaje;
        
        public ActualizaTablaAmortizacionAFechaProcResponse()
        {
        }
        
        public ActualizaTablaAmortizacionAFechaProcResponse(bool ActualizaTablaAmortizacionAFechaProcResult, string mensaje)
        {
            this.ActualizaTablaAmortizacionAFechaProcResult = ActualizaTablaAmortizacionAFechaProcResult;
            this.mensaje = mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DatosOrdenPagoRequest", WrapperNamespace="http://tecreemos.wcf.caja/xsd", IsWrapped=true)]
    public partial class DatosOrdenPagoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tecreemos.wcf.caja/xsd", Order=0)]
        public string credito;
        
        public DatosOrdenPagoRequest()
        {
        }
        
        public DatosOrdenPagoRequest(string credito)
        {
            this.credito = credito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DatosOrdenPagoResponse", WrapperNamespace="http://tecreemos.wcf.caja/xsd", IsWrapped=true)]
    public partial class DatosOrdenPagoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tecreemos.wcf.caja/xsd", Order=0)]
        public ServicioTcrCaja.OrdenPagoData[] ListaOrdenesPago;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tecreemos.wcf.caja/xsd", Order=1)]
        public int CodigoRespuesta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tecreemos.wcf.caja/xsd", Order=2)]
        public string Mensaje;
        
        public DatosOrdenPagoResponse()
        {
        }
        
        public DatosOrdenPagoResponse(ServicioTcrCaja.OrdenPagoData[] ListaOrdenesPago, int CodigoRespuesta, string Mensaje)
        {
            this.ListaOrdenesPago = ListaOrdenesPago;
            this.CodigoRespuesta = CodigoRespuesta;
            this.Mensaje = Mensaje;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface TcrCajaServiceChannel : ServicioTcrCaja.TcrCajaService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class TcrCajaServiceClient : System.ServiceModel.ClientBase<ServicioTcrCaja.TcrCajaService>, ServicioTcrCaja.TcrCajaService, IServicioReferenciaPago, IServicioOrdenPago
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TcrCajaServiceClient() : 
                base(TcrCajaServiceClient.GetDefaultBinding(), TcrCajaServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_TcrCajaService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TcrCajaServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(TcrCajaServiceClient.GetBindingForEndpoint(endpointConfiguration), TcrCajaServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TcrCajaServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TcrCajaServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TcrCajaServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TcrCajaServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TcrCajaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServicioTcrCaja.ConsultaPendientesResponse> ConsultaPendientesCajaAsync(ServicioTcrCaja.ConsultaPendientesCajaRequest request)
        {
            return base.Channel.ConsultaPendientesCajaAsync(request);
        }
        
        public System.Threading.Tasks.Task RefrescaParametrosAsync()
        {
            return base.Channel.RefrescaParametrosAsync();
        }
        
        public System.Threading.Tasks.Task<ServicioTcrCaja.ActualizaTablaAmortizacionAFechaProcResponse> ActualizaTablaAmortizacionAFechaProcAsync(ServicioTcrCaja.ActualizaTablaAmortizacionAFechaProcRequest request)
        {
            return base.Channel.ActualizaTablaAmortizacionAFechaProcAsync(request);
        }
        
        public System.Threading.Tasks.Task<string> ConsultaParametrosEspecialesAsync(string tipo)
        {
            return base.Channel.ConsultaParametrosEspecialesAsync(tipo);
        }
        
        public System.Threading.Tasks.Task<ServicioTcrCaja.RespuestaReferencia> GeneraReferenciaPagoAsync(string numCredito, string usuario)
        {
            return base.Channel.GeneraReferenciaPagoAsync(numCredito, usuario);
        }

        public System.Threading.Tasks.Task<ServDocumentos.Core.Dtos.DatosTcrCaja.RespuestaReferencia> ObtieneReferenciaPagoAsync(string numCredito, string usuario)
        {
            var temp = base.Channel.GeneraReferenciaPagoAsync(numCredito, usuario).Result;
            ServDocumentos.Core.Dtos.DatosTcrCaja.RespuestaReferencia referencia = new ServDocumentos.Core.Dtos.DatosTcrCaja.RespuestaReferencia();
            if (temp != null)
            {
                referencia.Codigo128Paynet = temp.Codigo128Paynet;
                referencia.Codigo128WalMart = temp.Codigo128WalMart;
                referencia.CodigoRespuesta = temp.CodigoRespuesta;
                referencia.Mensaje = temp.Mensaje;
                referencia.NoReferenciaPaynet = temp.NoReferenciaPaynet;
                referencia.NoReferenciaWalMart = temp.NoReferenciaWalMart;
                if (temp.DatosCredito != null)
                {
                    referencia.DatosCredito = new Core.Dtos.DatosTcrCaja.DatosCreditoReferencia();
                    referencia.DatosCredito.NoCliente = temp.DatosCredito.NoCliente;
                    referencia.DatosCredito.NoCredito = temp.DatosCredito.NoCredito;
                    referencia.DatosCredito.NoCuentaAhorro = temp.DatosCredito.NoCuentaAhorro;
                    referencia.DatosCredito.Nombre = temp.DatosCredito.Nombre;
                    referencia.DatosCredito.NombreComercial = temp.DatosCredito.NombreComercial;
                    referencia.DatosCredito.Producto = temp.DatosCredito.Producto;
                }
            }
            return System.Threading.Tasks.Task.Run(() =>
            {
                return referencia;
            });
        }

        
        public System.Threading.Tasks.Task<ServDocumentos.Core.Dtos.DatosTcrCaja.RespuestaOrdenPago> ObtieneDatosOrdenPagoAsync(string numCredito)
        {
            ServDocumentos.Repositorios.TCR.ServicioTcrCaja.DatosOrdenPagoRequest NumeroCredito = new ServDocumentos.Repositorios.TCR.ServicioTcrCaja.DatosOrdenPagoRequest() {credito = numCredito };
            var temp = base.Channel.ObtieneDatosOrdenPagoAsync(NumeroCredito).Result;
            ServDocumentos.Core.Dtos.DatosTcrCaja.RespuestaOrdenPago referencia = new ServDocumentos.Core.Dtos.DatosTcrCaja.RespuestaOrdenPago();
            if (temp != null)
            {
                referencia.CodigoRespuesta = temp.CodigoRespuesta;
                referencia.Mensaje = temp.Mensaje;              
                  
                if (temp.ListaOrdenesPago != null)
                {
                    referencia.ListaDatosOrdenPago = new List<Core.Dtos.DatosTcrCaja.DatosOrdenPago>();
                    foreach (ServDocumentos.Repositorios.TCR.ServicioTcrCaja.OrdenPagoData ordenPagoRes in temp.ListaOrdenesPago)
                    {
                       
                        Core.Dtos.DatosTcrCaja.DatosOrdenPago datoOrdenPago = new Core.Dtos.DatosTcrCaja.DatosOrdenPago() 
                        {
                            Banco = ordenPagoRes.Banco,
                            NumeroCliente =ordenPagoRes.cliente,
                            Concepto = ordenPagoRes.Concepto,
                            Nombre = ordenPagoRes.Beneficiario,
                            Monto = ordenPagoRes.Monto,
                            DiasVigencia = ordenPagoRes.DiasVigencia,
                            FechaOperacion = ordenPagoRes.FechaOperacion,
                            FechaVigencia = ordenPagoRes.FechaVigencia,
                            NumeroConvenio = ordenPagoRes.NoConvenio,
                            Referencia = ordenPagoRes.Referencia
                            
                            
                        };
                        referencia.ListaDatosOrdenPago.Add(datoOrdenPago);
                    }
                   
                }
            }
            return System.Threading.Tasks.Task.Run(() =>
            {
                return referencia;
            });
        }

        public System.Threading.Tasks.Task<ServicioTcrCaja.DatosOperacionCredito> ConsultaDatosOperacionCreditoAsync(string numCredito)
        {
            return base.Channel.ConsultaDatosOperacionCreditoAsync(numCredito);
        }
        
        public System.Threading.Tasks.Task<ServicioTcrCaja.ConsultaOperacionesResponse> ConsultaOperacionTransaccionAsync(string numCredito)
        {
            return base.Channel.ConsultaOperacionTransaccionAsync(numCredito);
        }
        
        public System.Threading.Tasks.Task<ServicioTcrCaja.CreditoPreautorizado> ConsultaCreditoPreautorizadoAsync(string numCredito)
        {
            return base.Channel.ConsultaCreditoPreautorizadoAsync(numCredito);
        }
        
        public System.Threading.Tasks.Task<string> ActualizaEstadoTranOffLineAsync(long idOffline, string nuevoEstadoOffline, string motivo)
        {
            return base.Channel.ActualizaEstadoTranOffLineAsync(idOffline, nuevoEstadoOffline, motivo);
        }
        
        public System.Threading.Tasks.Task<ServicioTcrCaja.DatosOrdenPagoResponse> ObtieneDatosOrdenPagoAsync(ServicioTcrCaja.DatosOrdenPagoRequest request)
        {
            return base.Channel.ObtieneDatosOrdenPagoAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_TcrCajaService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_TcrCajaService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:31547/Utilerias.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TcrCajaServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_TcrCajaService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TcrCajaServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_TcrCajaService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_TcrCajaService,
        }
    }
}
